### ISSUE TITLE
In Patient dashbaord , recent vitals are not loaded, its saying "Loading"

### ISSUE THREAD

**Issue by hardikk08** [Intelehealth/intelehealth-openmrs-ui#12]
_From @prithi69 on August 14, 2017 17:29_

_Copied from original issue: Intelehealth/intelehealth-openmrs-module#42_

**Comment by hardikk08** [comment]
_From @prithi69 on September 14, 2017 5:22_

So, i disabled from the patient dashboard screen.

**Comment by hardikk08** [comment]
Lets ditch the core app and create our own.

**Comment by hardikk08** [comment]
Use this json to make an app - 
{
	"id": "intelehealth.mostRecentVitals",
	"icon": "icon-vitals",
	"order": 1,
	"extensions": [{
		"id": "${project.parent.groupId}.${project.parent.artifactId}.mostRecentVitals.clinicianDashboardFirstColumn",
		"appId": "intelehealth.mostRecentVitals",
		"extensionPointId": "patientDashboard.firstColumnFragments",
		"extensionParams": {
			"fragment": "intelehealthPatientDashboard/recentVitals"
		}
	}]
}

The fragment should exist in intelehealthPatientDashboard directory

**Comment by nehagoel2** [comment]
changes to be made:
1. Build into omod
2. Include in first column fragments below recent visits.
