### ISSUE TITLE
Add a column for patients gender and age to the active patients screen

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/intelehealth-openmrs-ui#20]
It should be reported as "M, 50 yrs" or "F, 29 yrs"

**Comment by AmbujPandey** [comment]
i tested

**Comment by AmbujPandey** [comment]
@kundanmail55  Your view show 2 column, one for gender & one for age. Please merge it in a single column and display like "M, 50 yrs" or "F, 29 yrs".

**Comment by kundanmail55** [comment]
Neha asked for two different columns and she has already said oky to my screenshot. You just have to test it.

**Comment by AmbujPandey** [comment]
I tested it and it shows perfect in module .
