### ISSUE TITLE
Program managers need a list of patients by name seen in a particular month or week

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/intelehealth-openmrs-ui#22]
This should be a sort of a report - where the user can put in a start date and end date and the screen should return a list of patients seen between that start and end date

It should include their name, age, gender, village and which telemedicine clinic location they came to.
Richa can guide about writing the query.
Vibha can guide about the user need in detail.

**Comment by nehagoel2** [comment]
See if this can be done using the OpenMRS reporting module (System Administration > Advanced Administration > Reports)

**Comment by nehagoel2** [comment]
https://wiki.openmrs.org/display/docs/Reporting+Module

**Comment by AmbujPandey** [comment]
Hi, I tested all responsible test cases which shows the UI in the best manner and The reporting module shows the Patient & visits during this interval. Please have a look on OpenMRS Testing report.

**Comment by nehagoel2** [comment]
Tested - now working properly.
