### ISSUE TITLE
Doctors need a status indicator on active visit to know if the patient has been seen or not

### ISSUE THREAD

**Issue by vibhabhirud** [Intelehealth/intelehealth-openmrs-ui#28]
Re #518 on Android

**Comment by kundanmail55** [comment]
We will created our own encounter type which will trigger when doctor clicks on patient name on active visit. This will help to change our encounter type to 'Visit Node' and doctor can prescribe medication, follow-ups, test etc. 

And our encounter type 9 will be triggered on 'Submit' button which will resides at the bottom of the page.

This way we don't have to change our current logic of OpenMRS and android application.

**Comment by nehagoel2** [comment]
Rename encounter type 14 to "Visit Complete"
