### ISSUE TITLE
Multiple reload, while doctor provide prescription

### ISSUE THREAD

**Issue by AmbujPandey** [Intelehealth/intelehealth-openmrs-ui#62]
When the doctor tried to add diagnosis, the browser says 'If there are multiple reload, please contact your system admin'.
Dr. Baagh and @AmbujPandey also face the problem before, but @AmbujPandey  can't recognise the reason of cause.

**Comment by kundanmail55** [comment]
We need to check a few things.
1. Is this happen only entering diagnosis or in any other fragment.
2. Are other user/devices face the same problem at the same time.
3. Server logs. (when this happen).
4. Session check (for login user)
5. Http error while creating "Visit Note" encounter.
